import Head from "next/head";
import Hero from "../components/Layout/Hero";

function Home() {
  return (
    <div>
      <Head>
        <title>Arma tu Toque</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        heading="Arma tu Toque"
        message="Arma tu Toque descripción general."
      />
    </div>
  );
}

export default Home;
