import Head from "next/head";
import Adelanto from "../components/Layout/Adelanto";
import Hero from "../components/Layout/Hero";
import Why from "../components/Layout/Why";

const Home = () => {
  return (
    <div className="Index">
      <Head>
        <title>Arma tu Toque</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        heading="Arma tu Toque"
        message="Hacemos crecer tu comunidad. En contacto directo con tus fans."
      />
      <Why />
      <Adelanto />
    </div>
  );
}

export default Home;
